
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LABORATORIO
 */
public class jfrmSupport extends javax.swing.JFrame {

    /**
     * Creates new form jfrmSupport
     */
    public jfrmSupport() {
        initComponents();
        this.setLocationRelativeTo(null);//localizacion
        this.setTitle("MotherBoard");//Titulo
        this.setResizable(false);//cambiar tamaño
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblNomPiezas = new javax.swing.JLabel();
        jlblPiezas = new javax.swing.JLabel();
        jlblConcepto = new javax.swing.JLabel();
        jlblFuncion = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemAbrir = new javax.swing.JMenuItem();
        itemGuardar = new javax.swing.JMenuItem();
        itemSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 450));

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));

        jlblNomPiezas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jlblPiezas.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jlblPiezas.setForeground(new java.awt.Color(255, 255, 255));
        jlblPiezas.setText("PIEZAS DEL ORDENADOR");

        jlblConcepto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlblConcepto.setForeground(new java.awt.Color(255, 102, 0));

        jlblFuncion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlblFuncion.setForeground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblConcepto)
                            .addComponent(jlblNomPiezas)
                            .addComponent(jlblFuncion)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jlblPiezas)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jlblPiezas)
                .addGap(29, 29, 29)
                .addComponent(jlblNomPiezas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 361, Short.MAX_VALUE)
                .addComponent(jlblConcepto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblFuncion)
                .addGap(27, 27, 27))
        );

        jMenu1.setText("Archivo ");

        itemAbrir.setText("Abrir ");
        itemAbrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemAbrirMouseClicked(evt);
            }
        });
        itemAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(itemAbrir);

        itemGuardar.setText("Guardar");
        itemGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGuardarActionPerformed(evt);
            }
        });
        jMenu1.add(itemGuardar);

        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        jMenu1.add(itemSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Imagenes");

        jMenuItem4.setText("Placa Base");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Procesador");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Ram");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Cooler");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Fuente de Poder");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem3.setText("Disco Duro HDD");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem9.setText("Unidad SSD");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuItem10.setText("Tarjeta de Video GPU");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuItem11.setText("Tarjeta de Red");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuItem12.setText("Ventilador del Gabinete");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem12);

        jMenuItem13.setText("Tarjeta de Sonido");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem13);

        jMenuItem14.setText("Bateria CMOS");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem14);

        jMenuItem15.setText("Cable SATA");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem15);

        jMenuItem16.setText("Cable de Alimentación");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem16);

        jMenuItem17.setText("BIOS / UEFI");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem17);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");

        jMenuItem1.setText("Acerca del Programa");
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Créditos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
        jlblPiezas.setText("MotherBoard");
        jlblNomPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/motherboard.png")));
        jlblConcepto.setText("Concepto: El circuito impreso principal de la computadora.");
        jlblFuncion.setText("Función: Conectar y permitir la comunicación entre todos los componentes.");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
        jlblPiezas.setText("Procesador");
        jlblNomPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cpu.png")));
        jlblConcepto.setText("Concepto: El cerebro electrónico del sistema.");
        jlblFuncion.setText("Función: Ejecutar las instrucciones de los programas y procesar datos.");
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
        jlblPiezas.setText("RAM");
        jlblNomPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ram.png")));
        jlblConcepto.setText("Concepto: Memoria de acceso aleatorio de alta velocidad y temporal.");
        jlblFuncion.setText("Función: Almacenar los datos de los programas que usas en el momento.");
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
        jlblPiezas.setText("Cooler");
        jlblNomPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cooler.png")));
        jlblConcepto.setText("Concepto: Disipador térmico con ventilador montado sobre la CPU.");
        jlblFuncion.setText("Función: Absorber y disipar el calor, evitando que se queme.");
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
        jlblPiezas.setText("Fuente");
        jlblNomPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fuente.png")));
        jlblConcepto.setText("Concepto: El transformador de energía del equipo.");
        jlblFuncion.setText("Función: Convertir la corriente en la adecuada");
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void itemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAbrirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Funcionalidad Abrir");
    }//GEN-LAST:event_itemAbrirActionPerformed

    private void itemAbrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemAbrirMouseClicked

    }//GEN-LAST:event_itemAbrirMouseClicked

    private void itemGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGuardarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Funcionalidad Guardar");
    }//GEN-LAST:event_itemGuardarActionPerformed

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        // TODO add your handling code here:
        int opc = JOptionPane.showConfirmDialog(null, "¿Desea salir del sistema?");
        if (opc==0)
            System.exit(0);
    }//GEN-LAST:event_itemSalirActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
        jlblPiezas.setText("Disco Duro HDD");
        jlblNomPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hdd.png")));
        jlblConcepto.setText("Concepto: Dispositivo de almacenamiento magnético");
        jlblFuncion.setText("Función: Guardar todo permanentemente.");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
        jlblPiezas.setText("Unidad SSD");
        jlblNomPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ssd.png")));
        jlblConcepto.setText("Concepto: Dispositivo de almacenamiento moderno");
        jlblFuncion.setText("Función: Mismo rol que el HDD, pero con velocidades más rápidas.");
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
        jlblPiezas.setText("Tarjeta de Video (GPU)");
        jlblNomPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/gpu.png")));
        jlblConcepto.setText("Concepto: Procesador especializado en tareas visuales");
        jlblFuncion.setText("Función: Renderizar imágenes, videos y juegos");
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
        jlblPiezas.setText("Tarjeta de Red");
        jlblNomPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/red.png")));
        jlblConcepto.setText("Concepto: Interfaz de comunicación física o inalámbrica.");
        jlblFuncion.setText("Función: Conectar la computadora a internet");
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
        jlblPiezas.setText("Ventilador del Gabinete");
        jlblNomPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventilador.png")));
        jlblConcepto.setText("Concepto: Extractor de aire montado en la carcasa");
        jlblFuncion.setText("Función: Generar un flujo de aire para sacar el calor");
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
        jlblPiezas.setText("Tarjeta de Sonido");
        jlblNomPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sonido.png")));
        jlblConcepto.setText("Concepto: Chip o tarjeta, procesa audio");
        jlblFuncion.setText("Función: Convertir señales digitales en sonido");
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
        jlblPiezas.setText("Batería CMOS");
        jlblNomPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cmos.png")));
        jlblConcepto.setText("Concepto: Pequeña pila de botón en la placa base");
        jlblFuncion.setText("Función: Energizar chip de configuración básica");
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
        jlblPiezas.setText("Cable SATA");
        jlblNomPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sata.png")));
        jlblConcepto.setText("Concepto: Bus o cable de transferencia de datos");
        jlblFuncion.setText("Función: Conectar unidades de almacenamiento");
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
        jlblPiezas.setText("Cable de Alimentación");
        jlblNomPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alimentacion.png")));
        jlblConcepto.setText("Concepto: Conductores de corriente eléctrica");
        jlblFuncion.setText("Función: Llevar la energía desde la fuente");
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
        jlblPiezas.setText("");
        jlblPiezas.setText("BIOS / UEFI");
        jlblNomPiezas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bios.png")));
        jlblConcepto.setText("Concepto: Primer software que se ejecuta al encender");
        jlblFuncion.setText("Función: Verificar que el hardware básico funcione");
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Nelson Emiliano Cuevas Esquibel IVD 5");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmSupport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAbrir;
    private javax.swing.JMenuItem itemGuardar;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlblConcepto;
    private javax.swing.JLabel jlblFuncion;
    private javax.swing.JLabel jlblNomPiezas;
    private javax.swing.JLabel jlblPiezas;
    // End of variables declaration//GEN-END:variables
}
